import { ProfanityWord } from '../../types';

export const aceh: ProfanityWord[] = [
  {
    word: 'aneuk bajeung',
    category: 'insult',
    region: 'aceh',
    severity: 0.8,
    aliases: [],
    description: 'Secara harfiah berarti anak haram',
    context: 'Umpatan kasar untuk menghina status kelahiran seseorang',
  },
  {
    word: 'pukoe ma',
    category: 'sexual',
    region: 'aceh',
    severity: 0.9,
    aliases: ['pukoima', 'pukima'],
    description: 'Secara harfiah berarti kemaluan ibu',
    context: 'Umpatan sangat kasar yang menyerang ibu seseorang',
  },
  {
    word: 'ok ma',
    category: 'sexual',
    region: 'aceh',
    severity: 0.9,
    aliases: ['oek ma', 'uk ma'],
    description: 'Secara harfiah berarti setubuhi ibumu',
    context: 'Umpatan sangat kasar yang menyerang ibu seseorang',
  },
  {
    word: 'pap ma',
    category: 'sexual',
    region: 'aceh',
    severity: 0.9,
    aliases: ['papma'],
    description: 'Secara harfiah berarti setubuhi ibu',
    context:
      'Umpatan sangat kasar yang menyerang ibu seseorang (bentuk lain dari ok ma)',
  },
  {
    word: 'jak lét bui',
    category: 'insult',
    region: 'aceh',
    severity: 0.7,
    aliases: ['jak let bui'],
    description: 'Secara harfiah berarti pergi jilat babi',
    context: 'Umpatan kasar untuk mengusir atau menghina seseorang',
  },
  {
    word: 'bui',
    category: 'insult',
    region: 'aceh',
    severity: 0.6,
    aliases: [],
    description: 'Secara harfiah berarti babi',
    context:
      'Umpatan untuk menyebut orang yang dianggap kotor, rakus, atau tidak berakhlak',
  },
  {
    word: 'asèe',
    category: 'insult',
    region: 'aceh',
    severity: 0.6,
    aliases: ['asee'],
    description: 'Secara harfiah berarti anjing',
    context:
      'Umpatan untuk menyebut orang yang dianggap hina atau tidak berguna',
  },
  {
    word: 'thô bangai',
    category: 'insult',
    region: 'aceh',
    severity: 0.7,
    aliases: ['tho bangai'],
    description: 'Secara harfiah berarti sangat bodoh',
    context: 'Umpatan kasar untuk menyebut seseorang yang sangat tidak pintar',
  },
  {
    word: 'paléh',
    category: 'insult',
    region: 'aceh',
    severity: 0.5,
    aliases: [],
    description: 'Berarti licik atau celaka',
    context:
      'Umpatan untuk menyebut orang yang curang atau untuk menyatakan kekesalan',
  },
  {
    word: 'haramjadah',
    category: 'insult',
    region: 'aceh',
    severity: 0.8,
    aliases: [],
    description:
      'Berarti kurang ajar atau anak haram (lebih halus dari aneuk bajeung)',
    context:
      'Umpatan kasar untuk menyebut anak yang tidak sopan atau tidak beradab',
  },
  {
    word: 'lagèe bui',
    category: 'insult',
    region: 'aceh',
    severity: 0.6,
    aliases: ['lagee bui'],
    description: 'Secara harfiah berarti seperti babi',
    context: 'Umpatan untuk membandingkan seseorang dengan babi (jorok, rakus)',
  },
  {
    word: 'aneuk tét',
    category: 'sexual',
    region: 'aceh',
    severity: 0.8,
    aliases: [],
    description: 'Mengacu pada alat kelamin wanita (kasar)',
    context: 'Umpatan kasar yang merendahkan wanita',
  },
  {
    word: 'glanteutak',
    category: 'profanity',
    region: 'aceh',
    severity: 0.7,
    aliases: [],
    description: 'Artinya tidak jelas, digunakan sebagai umpatan kasar',
    context: 'Umpatan kasar yang sering diucapkan saat marah atau kesal',
  },
  {
    word: 'pukôe leumô',
    category: 'sexual',
    region: 'aceh',
    severity: 0.8,
    aliases: ['pukoe leumo'],
    description: 'Secara harfiah berarti kemaluan lembu',
    context:
      'Umpatan kasar, meskipun tidak sesering umpatan yang menyerang ibu',
  },
  {
    word: 'jak lét asèe',
    category: 'insult',
    region: 'aceh',
    severity: 0.7,
    aliases: ['jak let asee'],
    description: 'Secara harfiah berarti pergi jilat anjing',
    context: 'Umpatan kasar untuk mengusir atau menghina seseorang',
  },
  {
    word: 'bui seugot',
    category: 'insult',
    region: 'aceh',
    severity: 0.6,
    aliases: [],
    description: 'Secara harfiah berarti babi hutan',
    context: 'Umpatan untuk menyebut orang yang liar atau tidak terkontrol',
  },
  {
    word: 'dajeu',
    category: 'profanity',
    region: 'aceh',
    severity: 0.7,
    aliases: [],
    description: 'Mengacu pada sosok dajjal (jahat, penipu)',
    context: 'Umpatan untuk menyebut orang yang sangat jahat atau penipu',
  },
  {
    word: 'iblis paléh',
    category: 'profanity',
    region: 'aceh',
    severity: 0.7,
    aliases: [],
    description: 'Berarti iblis celaka',
    context: 'Umpatan untuk menyebut orang yang sangat buruk kelakuannya',
  },
  {
    word: 'lagèe peuraun',
    category: 'profanity',
    region: 'aceh',
    severity: 0.6,
    aliases: ['lagee peurawot'],
    description: 'Secara harfiah berarti seperti setan',
    context: 'Umpatan untuk menyebut orang yang nakal atau menjengkelkan',
  },
  {
    word: 'aneuk budok',
    category: 'insult',
    region: 'aceh',
    severity: 0.5,
    aliases: [],
    description: 'Secara harfiah berarti anak kera/monyet (kasar)',
    context: 'Umpatan untuk menyebut anak yang nakal atau tidak sopan',
  },
  {
    word: "pa'ak",
    category: 'insult',
    region: 'aceh',
    severity: 0.6,
    aliases: [],
    description: 'Berarti bodoh',
    context: 'Umpatan untuk menyebut seseorang yang tidak pintar',
  },
  {
    word: 'sangak',
    category: 'insult',
    region: 'aceh',
    severity: 0.6,
    aliases: [],
    description: "Berarti bodoh (lebih kasar dari pa'ak)",
    context: 'Umpatan kasar untuk menyebut seseorang yang sangat bodoh',
  },
  {
    word: 'utak udeung',
    category: 'insult',
    region: 'aceh',
    severity: 0.7,
    aliases: ['otak udang'],
    description: 'Secara harfiah berarti otak udang (bodoh)',
    context: 'Umpatan kasar untuk menyebut seseorang yang sangat bodoh',
  },
  {
    word: 'hana adab',
    category: 'insult',
    region: 'aceh',
    severity: 0.5,
    aliases: [],
    description: 'Berarti tidak beradab',
    context: 'Umpatan untuk menyebut seseorang yang tidak sopan',
  },
];

export const acehWords = aceh.map((item) => item.word);

export default aceh;