import { ProfanityWord } from '../../types';

export const batak: ProfanityWord[] = [
  {
    word: 'sundel',
    category: 'sexual',
    region: 'batak',
    severity: 0.8,
    aliases: ['sundal'],
    description: 'Kata kasar untuk menyebut pekerja seks komersial',
    context: 'Hinaan kasar untuk wanita',
  },
  {
    word: 'hambirang',
    category: 'insult',
    region: 'batak',
    severity: 0.7,
    aliases: [],
    description: "Secara harfiah berarti 'tidak berguna' atau 'sia-sia'",
    context: 'Umpatan kasar untuk menyebut orang yang dianggap tidak berguna atau tidak becus.',
  },
  {
    word: 'puki mak',
    category: 'sexual',
    region: 'batak',
    severity: 0.9,
    aliases: ['pukimak'],
    description: 'Secara harfiah berarti kemaluan ibu',
    context: 'Umpatan sangat kasar dan ofensif yang menyerang ibu seseorang.',
  },
  {
    word: 'puki',
    category: 'sexual',
    region: 'batak',
    severity: 0.8,
    aliases: [],
    description: 'Secara harfiah berarti kemaluan (kasar)',
    context: 'Umpatan kasar untuk menyebut kemaluan wanita.',
  },
  {
    word: 'pangongoi',
    category: 'insult',
    region: 'batak',
    severity: 0.6,
    aliases: [],
    description: 'Berarti pembohong atau penipu',
    context: 'Umpatan untuk menyebut orang yang tidak jujur.',
  },
  {
    word: 'bodat',
    category: 'insult',
    region: 'batak',
    severity: 0.6,
    aliases: [],
    description: 'Kata umpatan yang mengacu pada hewan monyet',
    context: 'Digunakan untuk menyebut orang yang dianggap bodoh atau tolol.',
  },
  {
    word: 'tullol',
    category: 'insult',
    region: 'batak',
    severity: 0.7,
    aliases: [],
    description: 'Berarti bodoh atau dungu (kasar)',
    context: 'Umpatan kasar untuk menyebut seseorang yang sangat tidak pintar.',
  },
  {
    word: 'jongos',
    category: 'insult',
    region: 'batak',
    severity: 0.7,
    aliases: [],
    description: 'Berarti pelayan atau pembantu (digunakan sebagai hinaan)',
    context: 'Umpatan kasar untuk merendahkan status sosial seseorang.',
  },
  {
    word: 'rime',
    category: 'disgusting',
    region: 'batak',
    severity: 0.6,
    aliases: [],
    description: 'Secara harfiah berarti kotoran atau najis',
    context: 'Umpatan untuk menunjukkan sesuatu yang menjijikkan atau buruk.',
  },
  {
    word: 'biang',
    category: 'insult',
    region: 'batak',
    severity: 0.7,
    aliases: [],
    description: 'Secara harfiah berarti induk anjing (kasar)',
    context: 'Umpatan kasar untuk menghina wanita.',
  },
  {
    word: 'anak ni biang',
    category: 'insult',
    region: 'batak',
    severity: 0.8,
    aliases: [],
    description: 'Secara harfiah berarti anak anjing (sangat kasar)',
    context: 'Umpatan sangat kasar untuk menghina seseorang.',
  },
  {
    word: 'mago',
    category: 'profanity',
    region: 'batak',
    severity: 0.6,
    aliases: [],
    description: 'Berarti hilang atau celaka',
    context: 'Umpatan untuk menunjukkan kekesalan atau harapan buruk.',
  },
  {
    word: 'loa-loa',
    category: 'insult',
    region: 'batak',
    severity: 0.5,
    aliases: [],
    description: 'Berarti orang yang suka bicara omong kosong atau tidak jelas',
    context: 'Umpatan ringan untuk menyebut orang yang perkataannya tidak bisa dipercaya.',
  },
  {
    word: 'loak',
    category: 'insult',
    region: 'batak',
    severity: 0.5,
    aliases: [],
    description: 'Berarti orang yang bodoh',
    context: 'Umpatan kasar untuk menyebut orang yang tidak pintar.',
  },
  {
    word: 'songon babiat',
    category: 'insult',
    region: 'batak',
    severity: 0.7,
    aliases: [],
    description: 'Secara harfiah berarti seperti binatang buas (kasar)',
    context: 'Umpatan kasar untuk menyebut orang yang kelakuannya buruk atau liar.',
  },
  {
    word: 'hau buluk',
    category: 'insult',
    region: 'batak',
    severity: 0.6,
    aliases: [],
    description: 'Secara harfiah berarti pohon lapuk (kiasan untuk tidak berguna)',
    context: 'Umpatan untuk menyebut orang yang dianggap tidak berguna.',
  },
  {
    word: 'bujang inam',
    category: 'sexual',
    region: 'batak',
    severity: 0.8,
    aliases: [],
    description: 'Secara harfiah berarti kemaluan (kasar)',
    context: 'Umpatan kasar untuk menyebut kemaluan wanita.',
  },
  {
    word: 'pilat',
    category: 'sexual',
    region: 'batak',
    severity: 0.8,
    aliases: [],
    description: 'Secara harfiah berarti kemaluan (kasar)',
    context: 'Umpatan kasar untuk menyebut kemaluan pria.',
  },
  {
    word: 'heang',
    category: 'sexual',
    region: 'batak',
    severity: 0.8,
    aliases: [],
    description: 'Secara harfiah berarti kemaluan (kasar)',
    context: 'Umpatan kasar untuk menyebut kemaluan wanita.',
  },
  {
    word: 'longor',
    category: 'insult',
    region: 'batak',
    severity: 0.7,
    aliases: [],
    description: 'Berarti bodoh atau dungu (kasar)',
    context: 'Umpatan kasar untuk menyebut seseorang yang sangat tidak pintar.',
  },
  {
    word: 'rojan',
    category: 'disgusting',
    region: 'batak',
    severity: 0.6,
    aliases: [],
    description: 'Secara harfiah berarti kotoran atau najis',
    context: 'Umpatan untuk menunjukkan sesuatu yang menjijikkan atau buruk.',
  },
  {
    word: 'teho',
    category: 'insult',
    region: 'batak',
    severity: 0.8,
    aliases: [],
    description: 'Secara harfiah berarti mengatakan kamu kayak tai)',
    context: 'Umpatan sangat kasar untuk menghina seseorang.',
  },
  {
    word: 'roa',
    category: 'insult',
    region: 'batak',
    severity: 0.8,
    aliases: [],
    description: 'Secara harfiah berarti mengatakan rupa yang jelek)',
    context: 'Umpatan sangat kasar untuk menghina seseorang.',
  },
  {
    word: 'pargabus',
    category: 'insult',
    region: 'batak',
    severity: 0.6,
    aliases: [],
    description: 'Berarti pembohong atau penipu',
    context: 'Umpatan untuk menyebut orang yang tidak jujur.',
  },
  {
    word: 'tois hian',
    category: 'insult',
    region: 'batak',
    severity: 0.8,
    aliases: [],
    description: 'Secara harfiah berarti mengatakan sombong kali)',
    context: 'Umpatan sangat kasar untuk menghina seseorang yang sombong.',
  },
  {
    word: 'rittik',
    category: 'insult',
    region: 'batak',
    severity: 0.8,
    aliases: [],
    description: 'Secara harfiah berarti mengatakan prilaku seperti orang gila)',
    context: 'Umpatan kasar untuk menghina seseorang yang dianggap seperti orang gila.',
  },
  {
    word: 'maup',
    category: 'insult',
    region: 'batak',
    severity: 0.8,
    aliases: [],
    description: 'Secara harfiah berarti mengatakan mampus(mati aja) aja kau)',
    context: 'Umpatan kasar untuk menghina seseorang yang sulit untuk diajari atau susah mengerti.',
  },
  {
    word: 'matami',
    category: 'profanity',
    region: 'batak',
    severity: 0.6,
    aliases: [],
    description: 'Berarti matamu tapi dengan nada kesal atau marah',
    context: 'Umpatan untuk menunjukkan kekesalan atau emosi karna dipandnag tidak layak.',
  },
  {
    word: 'pasib jo babam',
    category: 'profanity',
    region: 'batak',
    severity: 0.6,
    aliases: [],
    description: 'Berarti memerintahkan untuk diam dengan emosi',
    context: 'Umpatan untuk menunjukkan kekesalan atau emosi karna terlalu berisik.',
  },
  {
    word: 'hira begu',
    category: 'insult',
    region: 'batak',
    severity: 0.5,
    aliases: [],
    description: 'Secara harfiah berarti mengatakan kamu kayak setan(bisa karna prilakunya)',
    context: 'Umpatan kasar untuk menghina seseorang yang suka hilang tiba-tiba seperti setan.',
  },
  {
    word: 'bakke',
    category: 'profanity',
    region: 'batak',
    severity: 0.6,
    aliases: [],
    description: 'Berarti bangkai atau bau bangka',
    context:
      'Umpatan untuk menunjukkan kekesalan atau merasa heran kepada orng yang bau atau orang yang berantakan.',
  },
  {
    word: 'panakko',
    category: 'profanity',
    region: 'batak',
    severity: 0.6,
    aliases: [],
    description: 'Berarti si pencuri',
    context:
      'Umpatan untuk menunjukkan kekesalan atau emosi kepada orng suka mengambil tanpa permisi.',
  },
];

export const batakWords = batak.map((item) => item.word);

export default batak;
