import { ProfanityWord } from "../../types";

export const general: ProfanityWord[] = [
  {
    word: "anjing",
    category: "profanity",
    region: "general",
    severity: 0.7,
    aliases: ["anjay", "anjir", "anying", "njing", "anj", "anjg", "ajg"],
    description: "Mengacu pada hewan anjing, digunakan sebagai umpatan",
    context: "Umpatan umum untuk menunjukkan kemarahan atau ketidaksetujuan",
  },
  {
    word: "babi",
    category: "profanity",
    region: "general",
    severity: 0.6,
    aliases: ["bab1", "b4b1", "b4bi", "8481", "8ab1", "ba81"],
    description: "Mengacu pada hewan babi, digunakan sebagai umpatan",
    context: "Umpatan umum untuk menunjukkan kemarahan atau ketidaksetujuan",
  },
  {
    word: "bangsat",
    category: "insult",
    region: "general",
    severity: 0.8,
    aliases: ["bangst", "bngst", "bgst"],
    description:
      "Secara harfiah berarti kutu busuk, digunakan sebagai umpatan untuk menyebut seseorang yang tidak bermoral",
    context:
      "Umpatan kasar untuk menyebut orang yang dianggap jahat atau merugikan",
  },
  {
    word: "kontol",
    category: "sexual",
    region: "general",
    severity: 0.9,
    aliases: ["kntl", "k0ntol", "k0nt0l"],
    description: "Kata vulgar yang mengacu pada alat kelamin laki-laki",
    context: "Umpatan kasar atau istilah vulgar untuk alat kelamin",
  },
  {
    word: "memek",
    category: "sexual",
    region: "general",
    severity: 0.9,
    aliases: ["mmk", "memk"],
    description: "Kata vulgar yang mengacu pada alat kelamin perempuan",
    context: "Umpatan kasar atau istilah vulgar untuk alat kelamin",
  },
  {
    word: "bego",
    category: "insult",
    region: "general",
    severity: 0.5,
    aliases: ["bgo", "begok"],
    description: "Kata yang mengacu pada kebodohan seseorang",
    context: "Hinaan untuk menyebut orang yang dianggap tidak pintar",
  },
  {
    word: "tolol",
    category: "insult",
    region: "general",
    severity: 0.6,
    aliases: ["tll", "tlol"],
    description: "Kata yang mengacu pada kebodohan seseorang",
    context: "Hinaan untuk menyebut orang yang dianggap tidak pintar",
  },
  {
    word: "bajingan",
    category: "insult",
    region: "general",
    severity: 0.7,
    aliases: ["bajingn", "bjgn"],
    description: "Kata yang mengacu pada orang jahat atau tidak bermoral",
    context:
      "Hinaan untuk menyebut orang yang dianggap jahat atau tidak bermoral",
  },
  {
    word: "goblok",
    category: "insult",
    region: "general",
    severity: 0.6,
    aliases: ["gblk", "goblk"],
    description: "Kata yang mengacu pada kebodohan seseorang",
    context: "Hinaan untuk menyebut orang yang dianggap tidak pintar",
  },
  {
    word: "keparat",
    category: "insult",
    region: "general",
    severity: 0.7,
    aliases: ["kprt", "keprat"],
    description: "Kata yang mengacu pada orang jahat atau tidak bermoral",
    context:
      "Hinaan untuk menyebut orang yang dianggap jahat atau tidak bermoral",
  },
  {
    word: "bacot",
    category: "insult",
    region: "general",
    severity: 0.5,
    aliases: ["bcot", "bacot2"],
    description: "Kata yang mengacu pada orang yang banyak bicara",
    context: "Hinaan untuk menyebut orang yang banyak bicara atau cerewet",
  },
  {
    word: "ngentot",
    category: "sexual",
    region: "general",
    severity: 0.9,
    aliases: ["ngentod", "ntot", "tod"],
    description: "Istilah kasar untuk aktivitas seksual",
    context: "Kata vulgar yang merujuk pada aktivitas seksual",
  },
  {
    word: "sialan",
    category: "insult",
    region: "general",
    severity: 0.5,
    aliases: ["sialn", "sl"],
    description: "Kata yang mengacu pada orang yang membawa sial",
    context: "Hinaan untuk menyebut orang yang dianggap membawa sial",
  },
  {
    word: "pler",
    category: "sexual",
    region: "general",
    severity: 0.9,
    aliases: ["peler", "plr", "biji"],
    description: "Istilah kasar untuk alat kelamin laki-laki",
    context: "Kata vulgar yang merujuk pada alat kelamin laki-laki",
  },
  {
    word: "bokep",
    category: "sexual",
    region: "general",
    severity: 0.7,
    aliases: ["bkp", "bokap"],
    description: "Istilah untuk video atau konten pornografi",
    context: "Kata yang mengacu pada materi pornografi",
  },
  {
    word: "coli",
    category: "sexual",
    region: "general",
    severity: 0.8,
    aliases: ["col", "coly"],
    description: "Istilah untuk masturbasi laki-laki",
    context: "Kata vulgar yang merujuk pada aktivitas seksual pribadi",
  },
  {
    word: "desah",
    category: "sexual",
    region: "general",
    severity: 0.6,
    aliases: ["ds4h", "dsh"],
    description: "Istilah untuk suara yang dibuat selama aktivitas seksual",
    context: "Dapat menjadi vulgar tergantung konteks penggunaan",
  },
  {
    word: "seks",
    category: "sexual",
    region: "general",
    severity: 0.5,
    aliases: ["sex", "ML"],
    description: "Istilah untuk aktivitas seksual",
    context: "Dapat menjadi vulgar tergantung konteks penggunaan",
  },
  {
    word: "kondom",
    category: "sexual",
    region: "general",
    severity: 0.5,
    aliases: ["kndm", "kondom", "cd"],
    description: "Alat kontrasepsi",
    context: "Dapat menjadi vulgar tergantung konteks penggunaan",
  },
  {
    word: "ngewe",
    category: "sexual",
    region: "general",
    severity: 0.9,
    aliases: ["ngew", "we"],
    description: "Istilah kasar untuk aktivitas seksual",
    context: "Kata vulgar yang merujuk pada aktivitas seksual",
  },
  {
    word: "puki",
    category: "sexual",
    region: "general",
    severity: 0.9,
    aliases: ["puk", "pukih"],
    description: "Kata vulgar yang mengacu pada alat kelamin perempuan",
    context: "Kata vulgar yang merujuk pada anatomi seksual",
  },
  {
    word: "xxx",
    category: "sexual",
    region: "general",
    severity: 0.6,
    aliases: ["xXx", "triplex"],
    description:
      "Simbol yang sering digunakan untuk menandai konten pornografi",
    context: "Digunakan untuk menandai konten seksual eksplisit",
  },
  {
    word: "xnxx",
    category: "sexual",
    region: "general",
    severity: 0.6,
    aliases: ["xnxx", "xnx"],
    description: "simbol yang sering digunakan untuk menandai konten pornografi",
    context: "Digunakan untuk menandai konten seksual eksplisit",
  }
];

export const generalWords = general.map((item) => item.word);

export default general;
