import { ProfanityWord } from '../../types';

export const jawa: ProfanityWord[] = [
  {
    word: 'asu',
    category: 'profanity',
    region: 'jawa',
    severity: 0.7,
    aliases: ['asyu', 'su'],
    description: 'Secara harfiah berarti anjing dalam Bahasa Jawa',
    context: 'Umpatan umum dalam Bahasa Jawa untuk menunjukkan kemarahan',
  },
  {
    word: 'kirek',
    category: 'profanity',
    region: 'jawa',
    severity: 0.6,
    aliases: ['kirik'],
    description: 'Mengacu pada penyebutan anjing dalam Bahasa Jawa',
    context: 'Umpatan yang digunakan untuk menunjukkan kemarahan',
  },
  {
    word: 'jancok',
    category: 'sexual',
    region: 'jawa',
    severity: 0.9,
    aliases: ['jancuk', 'jncok', 'jancuk', 'jncuk', 'dancok', 'dancuk'],
    description: 'Kata umpatan kasar dalam Bahasa Jawa',
    context: 'Umpatan kasar yang umum digunakan di Jawa Timur',
  },
  {
    word: 'cuk',
    category: 'sexual',
    region: 'jawa',
    severity: 0.7,
    aliases: ['cok', 'cook'],
    description: 'Singkatan dari jancok/jancuk',
    context: 'Umpatan singkat yang umum digunakan di Jawa Timur',
  },
  {
    word: 'diancok',
    category: 'sexual',
    region: 'jawa',
    severity: 0.8,
    aliases: ['diancuk', 'dancok', 'ancok'],
    description: 'Variasi dari jancok/jancuk',
    context: 'Umpatan kasar yang umum digunakan di Jawa Timur',
  },
  {
    word: 'matamu',
    category: 'insult',
    region: 'jawa',
    severity: 0.5,
    aliases: ['mripat mu', 'matane'],
    description: 'Secara harfiah berarti matamu, digunakan sebagai umpatan ringan',
    context: 'Umpatan ringan untuk menanggapi sesuatu yang dianggap tidak benar',
  },
  {
    word: 'mbokne ancok',
    category: 'insult',
    region: 'jawa',
    severity: 0.9,
    aliases: ['mbokne', 'mbokneancok'],
    description: 'Umpatan yang menyinggung ibu seseorang',
    context: 'Umpatan kasar yang menyinggung orangtua orang lain',
  },
  {
    word: 'pekok',
    category: 'insult',
    region: 'jawa',
    severity: 0.7,
    aliases: ['pekak', 'pekilk'],
    description: 'Kata hinaan yang menunjukkan kebodohan',
    context: 'Hinaan untuk menyebut orang yang dianggap sangat bodoh',
  },
  {
    word: 'sempak',
    category: 'disgusting',
    region: 'jawa',
    severity: 0.5,
    aliases: ['sempok'],
    description: 'Mengacu pada pakaian dalam',
    context: 'Umpatan ringan yang dianggap jorok',
  },
  {
    word: 'taek',
    category: 'disgusting',
    region: 'jawa',
    severity: 0.6,
    aliases: ['tai', 'tahi', 'telek'],
    description: 'Secara harfiah berarti kotoran/tinja',
    context: 'Umpatan untuk menunjukkan sesuatu yang menjijikkan atau buruk',
  },
  {
    word: 'ndhasmu',
    category: 'insult',
    region: 'jawa',
    severity: 0.5,
    aliases: ['ndas mu', 'dhasmu'],
    description: 'Secara harfiah berarti kepalamu, digunakan sebagai umpatan ringan',
    context: 'Umpatan ringan untuk menanggapi sesuatu yang dianggap tidak benar',
  },
  {
    word: 'kontol',
    category: 'sexual',
    region: 'jawa',
    severity: 0.8,
    aliases: ['kntl', 'kontl'],
    description: 'Mengacu ke alat kelamin laki-laki',
    context: 'Kata vulgar yang sering digunakan sebagai umpatan kasar',
  },
  {
    word: 'tempek',
    category: 'sexual',
    region: 'jawa',
    severity: 0.8,
    aliases: ['mpek', 'torok', 'tempk'],
    description: 'Mengacu pada alat kelamin perempuan',
    context: 'Kata vulgar yang digunakan sebagai umpatan atau hinaan',
  },
  {
    word: 'silit',
    category: 'insult',
    region: 'jawa',
    severity: 0.6,
    aliases: ['selet', 'tilis'],
    description: 'Mengacu pada bagian dubur atau anus',
    context: 'Kata kasar yang digunakan sebagai hinaan',
  },
  {
    word: 'mbahmu',
    category: 'insult',
    region: 'jawa',
    severity: 0.6,
    aliases: ['mbahmu kiper', 'mbah mu'],
    description: 'Hinaan yang menyinggung nenek/kakek seseorang',
    context: 'Umpatan ringan untuk menanggapi sesuatu yang tidak masuk akal',
  },
  {
    word: 'makmu',
    category: 'insult',
    region: 'jawa',
    severity: 0.7,
    aliases: ['mak mu', 'mamamu'],
    description: 'Hinaan yang menyinggung ibu seseorang',
    context: 'Umpatan yang dianggap kasar karena menyinggung orang tua',
  },
  {
    word: 'bajingan',
    category: 'insult',
    region: 'jawa',
    severity: 0.7,
    aliases: ['bajilak', 'bajhingan', 'bajingak', 'bajingseng', 'bajindul', 'bajigur', 'jingan'],
    description: 'Sebutan untuk orang yang dianggap jahat atau tidak bermoral',
    context: 'Umpatan untuk mengekspresikan kemarahan atau kekesalan',
  },
  {
    word: 'cocote',
    category: 'insult',
    region: 'jawa',
    severity: 0.6,
    aliases: ['cocot', 'bacot', 'nyocot'],
    description: 'Mengacu pada mulut dengan konotasi negatif',
    context: 'Umpatan untuk menyuruh seseorang berhenti berbicara',
  },
  {
    word: 'ngentot',
    category: 'sexual',
    region: 'jawa',
    severity: 0.9,
    aliases: ['kentu', 'kentot', 'iclik', 'ngtt', 'iclk'],
    description: 'Mengacu pada aktivitas seksual',
    context: 'Kata vulgar yang digunakan sebagai umpatan kasar',
  },
  {
    word: 'edan',
    category: 'insult',
    region: 'jawa',
    severity: 0.5,
    aliases: ['gendeng', 'gila', 'gendheng', 'sarap'],
    description: 'Secara harfiah berarti gila atau tidak waras',
    context: 'Umpatan untuk menyebut seseorang yang dianggap tidak masuk akal',
  },
  {
    word: 'dapuranmu',
    category: 'insult',
    region: 'jawa',
    severity: 0.6,
    aliases: ['raimu', 'rai mu'],
    description: 'Secara harfiah mengacu pada wajah atau rupa seseorang',
    context: 'Umpatan untuk menghina penampilan atau wajah seseorang',
  },
  {
    word: 'damput',
    category: 'insult',
    region: 'jawa',
    severity: 0.7,
    aliases: ['diamput'],
    description: 'Variasi bentuk umpatan dengan makna serupa dengan jancok',
    context: 'Umpatan kasar untuk mengekspresikan kemarahan',
  },
  {
    word: 'mbathang',
    category: 'insult',
    region: 'jawa',
    severity: 0.7,
    aliases: ['mbatang'],
    description: 'Secara harfiah berarti bangkai',
    context: 'Umpatan kasar untuk menghina seseorang',
  },
  {
    word: 'ndlogok',
    category: 'insult',
    region: 'jawa',
    severity: 0.6,
    aliases: ['ndelodok', 'ndlodok'],
    description: 'Mengacu pada tindakan yang dianggap bodoh atau tidak masuk akal',
    context: 'Hinaan untuk mengkritik tindakan seseorang',
  },
  {
    word: 'nggateli',
    category: 'insult',
    region: 'jawa',
    severity: 0.5,
    aliases: ['gateli', 'gathel'],
    description: 'Secara harfiah berarti gatal atau menyebalkan',
    context: 'Ungkapan untuk menunjukkan kekesalan terhadap perilaku seseorang',
  },
  {
    word: 'perek',
    category: 'sexual',
    region: 'jawa',
    severity: 0.8,
    aliases: ['lonthe', 'pelacur'],
    description: 'Istilah merendahkan untuk pekerja seks komersial',
    context: 'Kata kasar untuk menghina wanita',
  },
  {
    word: 'picek',
    category: 'insult',
    region: 'jawa',
    severity: 0.6,
    aliases: ['pcek', 'buta'],
    description: 'Secara harfiah berarti buta atau tidak bisa melihat',
    context: 'Hinaan untuk orang yang dianggap tidak bisa melihat kenyataan',
  },
  {
    word: 'untumu',
    category: 'insult',
    region: 'jawa',
    severity: 0.5,
    aliases: ['gigimu', 'untu mu'],
    description: 'Secara harfiah berarti gigimu',
    context: 'Umpatan ringan untuk menanggapi sesuatu yang tidak disetujui',
  },
  {
    word: 'goblog',
    category: 'insult',
    region: 'jawa',
    severity: 0.7,
    aliases: ['ghoblog', 'goblok', 'gobhlok', 'pekok'],
    description: 'Kata hinaan yang menunjukkan kebodohan ekstrem',
    context: 'Hinaan untuk menyebut seseorang yang dianggap sangat bodoh',
  },
  {
    word: 'tolol',
    category: 'insult',
    region: 'jawa',
    severity: 0.7,
    aliases: ['tholol', 'tlol'],
    description: 'Kata hinaan yang menunjukkan kebodohan',
    context: 'Hinaan untuk menyebut seseorang yang dianggap bodoh',
  },
  {
    word: 'budheg',
    category: 'insult',
    region: 'jawa',
    severity: 0.6,
    aliases: ['budeg', 'bdeg'],
    description: 'Secara harfiah berarti tuli atau tidak bisa mendengar',
    context: 'Hinaan untuk orang yang dianggap tidak mau mendengarkan',
  },
  {
    word: 'jiangkrik',
    category: 'insult',
    region: 'jawa',
    severity: 0.4,
    aliases: ['jiangkrek', 'jangkrik'],
    description: 'Secara harfiah berarti jangkrik, digunakan sebagai eufemisme',
    context: 'Umpatan ringan sebagai pengganti kata kasar yang lebih vulgar',
  },
  {
    word: 'diamput',
    category: 'insult',
    region: 'jawa',
    severity: 0.8,
    aliases: ['damput', 'djamput'],
    description: 'Bentuk umpatan kasar dengan makna serupa jancok',
    context: 'Kata kasar untuk mengekspresikan kemarahan',
  },
  {
    word: 'celeng',
    category: 'insult',
    region: 'jawa',
    severity: 0.6,
    aliases: ['cleng', 'babi hutan'],
    description: 'Secara harfiah berarti babi hutan',
    context: 'Hinaan untuk orang yang dianggap jorok atau rakus',
  },
  {
    word: 'kampret',
    category: 'insult',
    region: 'jawa',
    severity: 0.5,
    aliases: ['kmpret', 'kmprt'],
    description: 'Secara harfiah berarti kelelawar kecil',
    context: 'Umpatan ringan untuk mengekspresikan kekesalan',
  },
  {
    word: 'ndeso',
    category: 'insult',
    region: 'jawa',
    severity: 0.4,
    aliases: ['ndesa', 'deso'],
    description: 'Secara harfiah berarti dari desa atau kampungan',
    context: 'Hinaan untuk orang yang dianggap kurang modern atau berpendidikan',
  },
  {
    word: 'kere',
    category: 'insult',
    region: 'jawa',
    severity: 0.5,
    aliases: ['miskin', 'mlarat'],
    description: 'Secara harfiah berarti miskin atau tidak punya uang',
    context: 'Hinaan untuk status ekonomi seseorang yang dianggap rendah',
  },
  {
    word: 'itil',
    category: 'sexual',
    region: 'jawa',
    severity: 0.9,
    aliases: ['itl', 'itul'],
    description: 'Kata vulgar yang mengacu pada bagian dari alat kelamin perempuan',
    context: 'Kata vulgar yang merujuk pada anatomi seksual',
  },
  {
    word: 'bodho',
    category: 'insult',
    region: 'jawa',
    severity: 0.6,
    aliases: ['bodo', 'bloon'],
    description: 'Secara harfiah berarti bodoh',
    context: 'Hinaan untuk menyebut seseorang yang kurang pintar atau tidak mengerti',
  },
  {
    word: 'doblok',
    category: 'insult',
    region: 'jawa',
    severity: 0.7,
    aliases: ['dobol'],
    description: 'Kata hinaan yang menunjukkan kebodohan',
    context: 'Hinaan kasar untuk orang yang dianggap sangat bodoh',
  },
  {
    word: 'cangkem asu',
    category: 'profanity',
    region: 'jawa',
    severity: 0.8,
    aliases: ['cangkemasu', 'cangkem su'],
    description: 'Secara harfiah berarti mulut anjing',
    context: 'Umpatan kasar yang ditujukan pada ucapan seseorang',
  },
  {
    word: 'rai gedheg',
    category: 'insult',
    region: 'jawa',
    severity: 0.6,
    aliases: ['raigedheg', 'rai gedeg'],
    description: 'Secara harfiah berarti muka tembok (tidak punya malu)',
    context: 'Hinaan untuk orang yang tidak tahu malu',
  },
  {
    word: 'kuping budheg',
    category: 'insult',
    region: 'jawa',
    severity: 0.6,
    aliases: ['kupingbudheg', 'kuping budeg'],
    description: 'Secara harfiah berarti telinga tuli',
    context: 'Hinaan untuk orang yang tidak mau mendengarkan',
  },
  {
    word: 'utek udang',
    category: 'insult',
    region: 'jawa',
    severity: 0.7,
    aliases: ['utekundang', 'otak udang'],
    description: 'Secara harfiah berarti otak udang (berarti bodoh)',
    context: 'Hinaan kasar untuk orang yang dianggap sangat bodoh',
  },
  {
    word: 'anak haram',
    category: 'insult',
    region: 'jawa',
    severity: 0.8,
    aliases: ['anakorok'],
    description: 'Sebutan menghina untuk anak yang lahir di luar pernikahan',
    context: 'Hinaan kasar yang menyerang status kelahiran seseorang',
  },
  {
    word: 'dajal',
    category: 'profanity',
    region: 'jawa',
    severity: 0.7,
    aliases: [],
    description: 'Mengacu pada sosok iblis atau penipu besar',
    context: 'Umpatan untuk menyebut orang yang sangat buruk atau jahat',
  },
  {
    word: 'setan',
    category: 'profanity',
    region: 'jawa',
    severity: 0.6,
    aliases: ['syetan'],
    description: 'Secara harfiah berarti setan',
    context: 'Umpatan untuk menunjukkan kekesalan atau menyebut orang yang nakal',
  },
  {
    word: 'blawur',
    category: 'insult',
    region: 'jawa',
    severity: 0.4,
    aliases: [],
    description: 'Menggambarkan kondisi yang tidak jelas atau linglung',
    context: 'Umpatan ringan untuk menyebut orang yang bingung atau tidak fokus',
  },
  {
    word: 'kemproh',
    category: 'disgusting',
    region: 'jawa',
    severity: 0.5,
    aliases: ['kumuh'],
    description: 'Menggambarkan sesuatu yang kotor dan tidak terawat',
    context: 'Umpatan ringan untuk menunjukkan sesuatu yang menjijikkan',
  },
  {
    word: 'mblekethek',
    category: 'insult',
    region: 'jawa',
    severity: 0.4,
    aliases: [],
    description: 'Menggambarkan sesuatu yang tidak beres atau tidak becus',
    context: 'Umpatan ringan untuk mengkritik sesuatu yang salah',
  },
  {
    word: 'nggragas',
    category: 'insult',
    region: 'jawa',
    severity: 0.5,
    aliases: [],
    description: 'Menggambarkan sifat rakus atau tamak',
    context: 'Umpatan ringan untuk menyebut orang yang serakah',
  },
  {
    word: 'kemlinthi',
    category: 'insult',
    region: 'jawa',
    severity: 0.4,
    aliases: ['kemaki'],
    description: 'Menggambarkan sifat sok pintar atau sombong',
    context: 'Umpatan ringan untuk menyebut orang yang pamer',
  },
];

export const jawaWords = jawa.map((item) => item.word);

export default jawa;
