import { ProfanityWord } from "../../types";

export const jawa: ProfanityWord[] = [
  {
    word: "asu",
    category: "profanity",
    region: "jawa",
    severity: 0.7,
    aliases: ["asyu", "su"],
    description: "Secara harfiah berarti anjing dalam Bahasa Jawa",
    context: "Umpatan umum dalam Bahasa Jawa untuk menunjukkan kemarahan",
  },
  {
    word: "jancok",
    category: "sexual",
    region: "jawa",
    severity: 0.8,
    aliases: ["jancuk", "jncok", "jancuk", "jncuk", "dancok", "dancuk"],
    description: "Kata umpatan kasar dalam Bahasa Jawa",
    context: "Umpatan kasar yang umum digunakan di Jawa Timur",
  },
  {
    word: "cuk",
    category: "sexual",
    region: "jawa",
    severity: 0.7,
    aliases: ["cok", "cook"],
    description: "Singkatan dari jancok/jancuk",
    context: "Umpatan singkat yang umum digunakan di Jawa Timur",
  },
  {
    word: "diancok",
    category: "sexual",
    region: "jawa",
    severity: 0.8,
    aliases: ["diancuk", "dancok", "ancok"],
    description: "Variasi dari jancok/jancuk",
    context: "Umpatan kasar yang umum digunakan di Jawa Timur",
  },
  {
    word: "matamu",
    category: "insult",
    region: "jawa",
    severity: 0.5,
    aliases: ["mripat mu", "matane"],
    description:
      "Secara harfiah berarti matamu, digunakan sebagai umpatan ringan",
    context:
      "Umpatan ringan untuk menanggapi sesuatu yang dianggap tidak benar",
  },
  {
    word: "mbokne ancok",
    category: "insult",
    region: "jawa",
    severity: 0.8,
    aliases: ["mbokne", "mbokneancok"],
    description: "Umpatan yang menyinggung ibu seseorang",
    context: "Umpatan kasar yang menyinggung orangtua orang lain",
  },
  {
    word: "pekok",
    category: "insult",
    region: "jawa",
    severity: 0.6,
    aliases: ["pekak", "pekilk"],
    description: "Kata hinaan yang menunjukkan kebodohan",
    context: "Hinaan untuk menyebut orang yang dianggap sangat bodoh",
  },
  {
    word: "sempak",
    category: "disgusting",
    region: "jawa",
    severity: 0.5,
    aliases: ["sempok"],
    description: "Mengacu pada pakaian dalam",
    context: "Umpatan ringan yang dianggap jorok",
  },
  {
    word: "taek",
    category: "disgusting",
    region: "jawa",
    severity: 0.6,
    aliases: ["tai", "tahi", "telek"],
    description: "Secara harfiah berarti kotoran/tinja",
    context: "Umpatan untuk menunjukkan sesuatu yang menjijikkan atau buruk",
  },
  {
    word: "ndhasmu",
    category: "insult",
    region: "jawa",
    severity: 0.5,
    aliases: ["ndas mu", "dhasmu"],
    description:
      "Secara harfiah berarti kepalamu, digunakan sebagai umpatan ringan",
    context:
      "Umpatan ringan untuk menanggapi sesuatu yang dianggap tidak benar",
  },
  {
    word: "kontol",
    category: "insult",
    region: "jawa",
    severity: 0.5,
    aliases: ["kntl", "kontl"],
    description: "mengacu ke alat kelamin laki laki",
    context: "",
  },
  {
    word: "tempek",
    category: "insult",
    region: "jawa",
    severity: 0.5,
    aliases: ["mpek", "torok", "tempk"],
    description: "mengacu pada alat kelmin perempuan",
    context: "",
  },
  {
    word: "silit",
    category: "insult",
    region: "jawa",
    severity: 0.5,
    aliases: ["selet", "tilis"],
    description: "",
    context: "",
  },
  {
    word: "mbahmu",
    category: "insult",
    region: "jawa",
    severity: 0.5,
    aliases: ["", ""],
    description: "",
    context: "umpatan ringan",
  },
  {
    word: "makmu",
    category: "insult",
    region: "jawa",
    severity: 0.5,
    aliases: ["", ""],
    description: "",
    context: "",
  },
  {
    word: "bajingan",
    category: "insult",
    region: "jawa",
    severity: 0.5,
    aliases: [
      "bajilak",
      "bajhingan",
      "bajingak",
      "bajingseng",
      "bajindul",
      "bajigur",
      "jingan",
    ],
    description: "",
    context: "",
  },
  {
    word: "cocote",
    category: "insult",
    region: "jawa",
    severity: 0.5,
    aliases: ["cocot", "bacot", "nyocot"],
    description: "",
    context: "",
  },
  {
    word: "ngentot",
    category: "insult",
    region: "jawa",
    severity: 0.5,
    aliases: ["kentu", "kentot", "iclik", "ngtt", "iclk"],
    description: "",
    context: "",
  },
  {
    word: "edan",
    category: "insult",
    region: "jawa",
    severity: 0.5,
    aliases: ["gendeng", "gila", "gendheng", "sarap"],
    description: "",
    context: "",
  },
  {
    word: "dapuranmu",
    category: "insult",
    region: "jawa",
    severity: 0.5,
    aliases: ["raimu", "rai mu"],
    description: "",
    context: "",
  },
  {
    word: "damput",
    category: "insult",
    region: "jawa",
    severity: 0.5,
    aliases: ["diamput"],
    description: "",
    context: "",
  },
  {
    word: "mbathang",
    category: "insult",
    region: "jawa",
    severity: 0.5,
    aliases: ["mbatang"],
    description: "",
    context: "",
  },
  {
    word: "ndlogok",
    category: "insult",
    region: "jawa",
    severity: 0.5,
    aliases: ["ndelodok", "ndlodok"],
    description: "",
    context: "",
  },
  {
    word: "nggateli",
    category: "insult",
    region: "jawa",
    severity: 0.5,
    aliases: ["gateli", "gathel"],
    description: "",
    context: "",
  },
  {
    word: "perek",
    category: "insult",
    region: "jawa",
    severity: 0.5,
    aliases: [""],
    description: "",
    context: "",
  },
  {
    word: "picek",
    category: "insult",
    region: "jawa",
    severity: 0.5,
    aliases: ["pcek", ""],
    description: "",
    context: "",
  },
  {
    word: "untumu",
    category: "insult",
    region: "jawa",
    severity: 0.5,
    aliases: ["gigimu a"],
    description: "",
    context: "",
  },
  {
    word: "goblog",
    category: "insult",
    region: "jawa",
    severity: 0.5,
    aliases: ["ghoblog", "goblok", "gobhlok", "pekok"],
    description: "",
    context: "",
  },
  {
    word: "tolol",
    category: "insult",
    region: "jawa",
    severity: 0.5,
    aliases: ["tholol", "tlol"],
    description: "",
    context: "",
  },
  {
    word: "budheg",
    category: "insult",
    region: "jawa",
    severity: 0.5,
    aliases: ["budeg", "bdeg"],
    description: "",
    context: "",
  },
  {
    word: "jiangkrik",
    category: "insult",
    region: "jawa",
    severity: 0.5,
    aliases: ["jiangkrek", ""],
    description: "",
    context: "",
  },
  {
    word: "diamput",
    category: "insult",
    region: "jawa",
    severity: 0.5,
    aliases: ["damput", "djamput"],
    description: "",
    context: "",
  },
  {
    word: "celeng",
    category: "insult",
    region: "jawa",
    severity: 0.5,
    aliases: ["cleng"],
    description: "",
    context: "",
  },
  {
    word: "kampret",
    category: "insult",
    region: "jawa",
    severity: 0.5,
    aliases: ["kmpret", "kmprt"],
    description: "",
    context: "",
  },
  {
    word: "ndeso",
    category: "insult",
    region: "jawa",
    severity: 0.5,
    aliases: ["", ""],
    description: "",
    context: "",
  },
  {
    word: "kere",
    category: "insult",
    region: "jawa",
    severity: 0.5,
    aliases: ["", ""],
    description: "",
    context: "",
  },
  {
    word: "itil",
    category: "sexual",
    region: "jawa",
    severity: 0.9,
    aliases: ["itl", "itul"],
    description:
      "Kata vulgar yang mengacu pada bagian dari alat kelamin perempuan",
    context: "Kata vulgar yang merujuk pada anatomi seksual",
  },
];

export const jawaWords = jawa.map((item) => item.word);

export default jawa;
