import { ProfanityWord } from '../../types';

export const sunda: ProfanityWord[] = [
  {
    word: 'bagong',
    category: 'insult',
    region: 'sunda',
    severity: 0.5,
    aliases: ['bagog'],
    description: 'Secara harfiah berarti babi hutan, digunakan sebagai hinaan',
    context: 'Hinaan untuk menyebut orang yang dianggap jorok atau rakus',
  },
  {
    word: 'belegug',
    category: 'insult',
    region: 'sunda',
    severity: 0.5,
    aliases: ['belecuk', 'beledog'],
    description: 'Kata yang mengacu pada kebodohan seseorang',
    context: 'Hinaan untuk menyebut orang yang dianggap tidak pintar',
  },
  {
    word: 'goblog',
    category: 'insult',
    region: 'sunda',
    severity: 0.6,
    aliases: ['goblok', 'golbok'],
    description: 'Kata yang mengacu pada kebodohan seseorang',
    context: 'Hinaan untuk menyebut orang yang dianggap tidak pintar',
  },
  {
    word: 'aing',
    category: 'insult',
    region: 'sunda',
    severity: 0.3,
    aliases: [],
    description: 'Kata ganti orang pertama yang kasar',
    context: 'Digunakan saat berbicara dengan teman dekat, tapi termasuk kasar',
  },
  {
    word: 'sia',
    category: 'insult',
    region: 'sunda',
    severity: 0.3,
    aliases: ['silaing'],
    description: 'Kata ganti orang kedua yang kasar',
    context: "Digunakan sebagai pengganti 'kamu' dalam bentuk kasar",
  },
  {
    word: 'anjing',
    category: 'profanity',
    region: 'sunda',
    severity: 0.8,
    aliases: ['anying'],
    description: 'Kata umpatan yang sangat umum',
    context: 'Digunakan dalam berbagai konteks: marah, kaget, bahkan kagum',
  },
  {
    word: 'anjir',
    category: 'profanity',
    region: 'sunda',
    severity: 0.6,
    aliases: [],
    description: 'Turunan dari kata anjing yang lebih halus',
    context: 'Digunakan saat kesal, marah, terpesona',
  },
  {
    word: 'kehed',
    category: 'insult',
    region: 'sunda',
    severity: 0.6,
    aliases: [],
    description: 'Sialan',
    context: 'Digunakan sebagai ungkapan kekesalan',
  },
  {
    word: 'modar',
    category: 'profanity',
    region: 'sunda',
    severity: 0.7,
    aliases: [],
    description: 'Secara harfiah berarti mati',
    context: 'Digunakan sebagai ungkapan kemarahan atau ancaman',
  },
  {
    word: 'koplok',
    category: 'insult',
    region: 'sunda',
    severity: 0.6,
    aliases: [],
    description: 'Setara dengan kata goblok',
    context: 'Digunakan sebagai kata umpatan untuk menyebut orang bodoh',
  },
  {
    word: 'beungeut',
    category: 'insult',
    region: 'sunda',
    severity: 0.5,
    aliases: [],
    description: 'Kata kasar untuk muka/wajah',
    context: 'Digunakan untuk menghina wajah seseorang',
  },
  {
    word: 'lebok',
    category: 'insult',
    region: 'sunda',
    severity: 0.5,
    aliases: [],
    description: 'Kata kasar untuk makan',
    context: "Digunakan dalam konteks 'rasakan' atau 'makan tuh'",
  },
  {
    word: 'ontohod',
    category: 'insult',
    region: 'sunda',
    severity: 0.5,
    aliases: [],
    description: 'Kata yang mengacu pada kebodohan seseorang',
    context: 'Populer dari cerita Kabayan sebagai ungkapan untuk orang bodoh',
  },
  {
    word: 'ngajedog',
    category: 'insult',
    region: 'sunda',
    severity: 0.4,
    aliases: [],
    description: "Bentuk kasar dari 'diam'",
    context: 'Digunakan untuk menyuruh seseorang diam dengan kasar',
  },
  {
    word: 'halik',
    category: 'insult',
    region: 'sunda',
    severity: 0.5,
    aliases: [],
    description: "Bentuk kasar dari 'awas'",
    context: 'Digunakan untuk menggertak atau mengusir orang',
  },
  {
    word: 'sungut',
    category: 'insult',
    region: 'sunda',
    severity: 0.5,
    aliases: ['babangus'],
    description: 'Kata kasar untuk mulut',
    context: 'Digunakan untuk menghina cara bicara seseorang',
  },
  {
    word: 'belekok',
    category: 'insult',
    region: 'sunda',
    severity: 0.5,
    aliases: [],
    description: 'Kata yang mengacu pada kebodohan seseorang',
    context: 'Serupa dengan belegug atau goblok',
  },
  {
    word: 'boloho',
    category: 'insult',
    region: 'sunda',
    severity: 0.4,
    aliases: [],
    description: 'Kata yang mengacu pada kebodohan seseorang',
    context: 'Versi lebih halus dari kata bodoh',
  },
  {
    word: 'bebel',
    category: 'insult',
    region: 'sunda',
    severity: 0.5,
    aliases: [],
    description: 'Setara dengan kehed',
    context: 'Digunakan untuk mengekspresikan kekesalan',
  },
  {
    word: 'hakan',
    category: 'insult',
    region: 'sunda',
    severity: 0.5,
    aliases: [],
    description: 'Kata kasar untuk makan',
    context: "Digunakan dalam konteks 'rasakan' atau 'makan tuh'",
  },
  {
    word: 'bagoy',
    category: 'insult',
    region: 'sunda',
    severity: 0.5,
    aliases: [],
    description: 'Turunan dari kata Bagong',
    context: 'Umum digunakan di Priangan Barat seperti Cianjur dan Sukabumi',
  },
  {
    word: 'pehul',
    category: 'insult',
    region: 'sunda',
    severity: 0.6,
    aliases: ['peot hulu'],
    description:
      "Akronim dari 'peot hulu', menghina seseorang tidak punya otak",
    context: 'Digunakan untuk menghina kecerdasan seseorang',
  },
  {
    word: 'pamatuk',
    category: 'insult',
    region: 'sunda',
    severity: 0.5,
    aliases: [],
    description: 'Paruh pada unggas',
    context: 'Digunakan untuk mengumpat orang yang banyak bicara',
  },
  {
    word: 'itil',
    category: 'sexual',
    region: 'sunda',
    severity: 0.9,
    aliases: [],
    description: 'Kata sangat kasar untuk alat kelamin perempuan',
    context: 'Kata vulgar yang sangat tabu',
  },
  {
    word: 'nyingkah',
    category: 'insult',
    region: 'sunda',
    severity: 0.5,
    aliases: [],
    description: 'Cara kasar untuk menyuruh pergi',
    context: 'Digunakan untuk mengusir orang',
  },
  {
    word: 'mantog',
    category: 'insult',
    region: 'sunda',
    severity: 0.4,
    aliases: [],
    description: 'Kata kasar untuk pulang',
    context: 'Biasanya diucapkan orang tua kepada anak yang tak kunjung pulang',
  },
  {
    word: 'cungur',
    category: 'insult',
    region: 'sunda',
    severity: 0.6,
    aliases: [],
    description: 'Kata kasar untuk mulut',
    context: 'Digunakan untuk menghina cara bicara seseorang',
  },
  {
    word: 'bangkawarah',
    category: 'insult',
    region: 'sunda',
    severity: 0.6,
    aliases: ['si bangkawarah'],
    description: 'Sebutan untuk orang yang nakal keterlaluan',
    context: 'Menunjukkan orang yang tidak mendapat pendidikan baik',
  },
  {
    word: 'bolokotondo',
    category: 'insult',
    region: 'sunda',
    severity: 0.6,
    aliases: [],
    description: 'Kutu, dipakai sebagai kata kasar',
    context: "Seperti 'bangsat' dalam bahasa Indonesia",
  },
  {
    word: 'babatok',
    category: 'insult',
    region: 'sunda',
    severity: 0.5,
    aliases: [],
    description: 'Tempurung kepala',
    context: 'Digunakan untuk menghina kecerdasan seseorang',
  },
  {
    word: 'polo',
    category: 'insult',
    region: 'sunda',
    severity: 0.6,
    aliases: [],
    description: 'Otak secara fisik',
    context: 'Dikatakan untuk isi kepala binatang, kasar jika untuk manusia',
  },
  {
    word: 'gubug',
    category: 'insult',
    region: 'sunda',
    severity: 0.4,
    aliases: ['ngagubug'],
    description: 'Mengambil tanpa permisi',
    context: 'Menuduh seseorang mengambil barang tanpa ijin',
  },
  {
    word: 'padog',
    category: 'insult',
    region: 'sunda',
    severity: 0.5,
    aliases: ['madog'],
    description: 'Mencuri',
    context: 'Kata kasar yang menuduh seseorang mencuri',
  },
  {
    word: 'kokod',
    category: 'insult',
    region: 'sunda',
    severity: 0.4,
    aliases: [],
    description: 'Kata kasar untuk tangan',
    context:
      'Digunakan untuk memarahi orang yang tidak sopan menggunakan tangan',
  },
  {
    word: 'cokor',
    category: 'insult',
    region: 'sunda',
    severity: 0.4,
    aliases: [],
    description: 'Kata kasar untuk kaki',
    context: 'Digunakan untuk memarahi orang yang tidak sopan menggunakan kaki',
  },
  {
    word: 'nyatu',
    category: 'insult',
    region: 'sunda',
    severity: 0.4,
    aliases: [],
    description: 'Kata kasar untuk makan',
    context: 'Seperti cara makan hewan, sangat kasar jika untuk manusia',
  },
  {
    word: 'lolodok',
    category: 'insult',
    region: 'sunda',
    severity: 0.5,
    aliases: [],
    description: 'Makan dengan cara berisik',
    context: 'Menghina cara makan seseorang yang seperti unggas',
  },
  {
    word: 'soblog',
    category: 'insult',
    region: 'sunda',
    severity: 0.6,
    aliases: [],
    description: 'Turunan dari goblog atau goblok',
    context: 'Digunakan sebagai penghinaan untuk menyebut orang bodoh',
  },
  {
    word: 'heunceut beureum',
    category: 'sexual',
    region: 'sunda',
    severity: 1.0,
    aliases: [],
    description: 'Kata yang sangat vulgar dan tabu',
    context: 'Sangat tidak pantas diucapkan di tempat umum',
  },
];

export const sundaWords = sunda.map((item) => item.word);

export default sunda;
