name: Create Release on Publish

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - name: Get current version from package.json
        id: package-version
        run: echo "PACKAGE_VERSION=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Create Git Tag
        run: |
          git tag -a "v${{ steps.package-version.outputs.PACKAGE_VERSION }}" -m "Release v${{ steps.package-version.outputs.PACKAGE_VERSION }}"
          git push origin "v${{ steps.package-version.outputs.PACKAGE_VERSION }}"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.package-version.outputs.PACKAGE_VERSION }}
          release_name: Release v${{ steps.package-version.outputs.PACKAGE_VERSION }}
          body: |
            Rilis versi ${{ steps.package-version.outputs.PACKAGE_VERSION }}
            - Fitur baru
            - Perbaikan bug
          draft: false
          prerelease: false